[pytest]
testpaths = tests
log_cli = true
log_cli_level = INFO
addopts = --alluredir=reports/allure-results
pythonpath = .
markers =
    smoke: Quick sanity tests
    regression: Full regression suite
    negative: Negative/edge case tests